// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afuqznhnzikagbamaaqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmdXF6bmhuemlrYWdiYW1hYXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTE1MzksImV4cCI6MjA3MzA4NzUzOX0.31eNL4tJWJ4hdJxq3DtPB6gwSThi_IC0LFv6CPrbv-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});